name: Build AMXX Module

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-windows:
    runs-on: windows-latest
    name: Build for Windows (x86)

    steps:
    - name: Checkout bcrypt repository
      uses: actions/checkout@v4
      with:
        path: bcrypt

    - name: Get submodules
      working-directory: ./bcrypt
      run: git submodule update --init --recursive

    - name: Configure CMake
      working-directory: ./bcrypt
      run: cmake -B build -G "Visual Studio 17 2022" -A Win32

    - name: Build with CMake
      working-directory: ./bcrypt
      run: cmake --build build --config Release

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: bcrypt_amxx-windows
        path: bcrypt/build/Release/bcrypt_amxx.dll

  build-linux:
    runs-on: ubuntu-22.04
    name: Build for Linux (x86)

    steps:
    - name: Checkout bcrypt repository
      uses: actions/checkout@v4
      with:
        path: bcrypt

    - name: Get submodules
      working-directory: ./bcrypt
      run: git submodule update --init --recursive
        
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-multilib build-essential cmake

    - name: Configure CMake
      working-directory: ./bcrypt
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build with CMake
      working-directory: ./bcrypt
      run: cmake --build build

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: bcrypt_amxx-linux
        path: bcrypt/build/bcrypt_amxx_i386.so